Create Vite. Add file styles.css. Edit file App.jsx, crate file Todo.…
dungtrantien302/6.Simple-Todo-List pull request #1
Opened 2024-04-18 12:05 UTC by dungtrantien302

1. Add todo to list todos

2024-04-18 12:16 UTC, dungtrantien302 commented
Add the ability to mark a todo as complete

2024-04-18 12:24 UTC, dungtrantien302 commented
Add a delete button next to each todo

2024-04-19 18:38 UTC, manhcuongdtbk requested changes

2024-04-19 18:38 UTC, manhcuongdtbk commented on vite/src/App.jsx
> +
a bỏ các dòng trống thừa giống chỗ này nhé

2024-04-19 18:38 UTC, manhcuongdtbk commented on vite/src/App.jsx
> +//   const [listTodos, setListTodos] = useState([])
a đổi tên biến lại thành `todos` là đủ ý nghĩa rồi

2024-04-19 18:38 UTC, manhcuongdtbk commented on vite/src/App.jsx
> +//         <button onClick={() => addNewTodo(todoInput)}>Add Todo</button>
`todoInput` là state nên a ko cần truyền vào `addNewTodo` ở đây. a có thể dùng thẳng `todoInput` trong `addNewTodo` function

2024-04-19 18:38 UTC, manhcuongdtbk commented on vite/src/App.jsx
> +//         {listTodos.map(todo => {
function truyền vào `map` chỉ có 1 dòng và chỉ là dòng `return` nên có thể viết tắt chỗ này thành 
```javascript
todos.map(todo => <Todo key={todo.id} name={todo.name} />
```

lưu ý đặt tên prop của `Todo` component cho khớp với ý nghĩa thực. `newTodo` thường đại diện cho 1 todo mới, không phải tên của todo

2024-04-19 18:38 UTC, manhcuongdtbk commented on vite/src/App.jsx
> +//         <label htmlFor="todo-input" id='todo-input'>New Todo</label>
tại sao ở đây lại cần `id` attribute vậy a? và tại sao `id` attribute ở đây lại có value giống với `input` bên dưới nhỉ?

2024-04-19 18:38 UTC, manhcuongdtbk commented on vite/src/App.jsx
> +//2 Add the ability to mark a todo as complete
các đầu mục 1, 2, 3 là các yêu cầu a cần làm. để hoàn thiện bài tập cần hoàn thiện đủ các chức năng theo yêu cầu, không phải tách thành từng đoạn code cho từng yêu cầu thế này

2024-04-19 18:38 UTC, manhcuongdtbk commented on vite/src/App.jsx
> +//   let [idTodo, setIdTodo] = useState(0)
2 giá trị lấy ra từ `useState` không bao giờ thay đổi trong code của mình nên không dùng `let` ở đây. luôn dùng `const`. việc thay đổi giá trị do React quản lý, mình chỉ gọi set function (ví dụ ở đây là `setIdTodo`) còn việc thay đổi thế nào, cập nhật giá trị mới ra sao đều do React làm

2024-04-19 18:38 UTC, manhcuongdtbk commented on vite/src/App.jsx
> +//   const [todoProces, setTodoProces] = useState({})
tại sao `todoProces` lại phải là state?

2024-04-19 18:38 UTC, manhcuongdtbk commented on vite/src/App.jsx
> +  function deleteTodo(idTodo) {
thường thì event handler trong react sẽ đặt tên theo dạng `onDeleteTodo` hoặc `deleteTodoHandler`

2024-04-20 00:19 UTC, dungtrantien302 commented on vite/src/App.jsx
> +
a bỏ rồi nhé

2024-04-20 00:19 UTC, dungtrantien302 commented on vite/src/App.jsx
> +//   const [listTodos, setListTodos] = useState([])
a đổi tên biến rồi nhé

2024-04-20 00:22 UTC, dungtrantien302 commented on vite/src/App.jsx
> +//         <button onClick={() => addNewTodo(todoInput)}>Add Todo</button>
a sửa lại function addNewTodo để dùng luôn todoInput rồi nhé

2024-04-20 00:23 UTC, dungtrantien302 commented on vite/src/App.jsx
> +//         {listTodos.map(todo => {
a sửa lại code và sửa tên prop của Todo component rồi nhé

2024-04-20 00:24 UTC, dungtrantien302 commented on vite/src/App.jsx
> +//         <label htmlFor="todo-input" id='todo-input'>New Todo</label>
Chỗ này a sai, id không được trùng nhau.

2024-04-20 00:24 UTC, dungtrantien302 commented on vite/src/App.jsx
> +//2 Add the ability to mark a todo as complete
a gộp lại rồi nhé

2024-04-20 00:24 UTC, dungtrantien302 commented on vite/src/App.jsx
> +//   let [idTodo, setIdTodo] = useState(0)
a sửa lại khai báo biến rồi nhé

2024-04-20 00:27 UTC, dungtrantien302 commented on vite/src/App.jsx
> +//   const [todoProces, setTodoProces] = useState({})
todoProces không cần phải là state, a khai báo lại thành biến cục bộ trong function addNewTodo

2024-04-20 00:30 UTC, dungtrantien302 commented on vite/src/App.jsx
> +  function deleteTodo(idTodo) {
A đặt lại tên rồi nhé

2024-04-20 04:40 UTC, merged